# Generated by Django 6.0 on 2026-01-24 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uncomplted_task",
            old_name="is_complted",
            new_name="is_completed",
        ),
    ]
