# Generated by Django 6.0 on 2026-01-24 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_rename_is_complted_uncomplted_task_is_completed"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Uncomplted_Task",
            new_name="Uncompleted_Task",
        ),
    ]
